chore: run Amplify smoke tests only on Node 20 (#604)
On recent Node 22s, they fail with the following weird error:

```
 [BackendBuildError] Unable to deploy due to CDK Assembly Error
    ∟ Caused by: [_AssemblyError] Assembly builder failed
  Error: aused by: [Error] ENOENT: no such file or directory, open '/tmp/cdk-integ-0dbc757n71oo/node_modules/@aws-amplify/backend-output-storage/lib/index.js?tsx-namespace=1749655833950'
```

---
By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache-2.0 license