fix: update python init templates dev dep on pytest to latest (#930)
Python templates started failing with:

```
ImportError: cannot import name 'Config' from 'pytest'
```

Updating to latest `pytest` dev-dep on local repro fixes this error.

---
By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache-2.0 license