fix(cdk-assets): `docker-credential-cdk-assets` cannot be invoked as a program (#661)
Ever since https://github.com/aws/aws-cdk-cli/pull/603, the file
references an external package that is not installed during installation
of `cdk-assets`. This causes:

```console
Error: Cannot find module '@aws-cdk/cdk-assets-lib'
Require stack:
- /usr/local/lib/node_modules/cdk-assets/bin/docker-credential-cdk-assets.js
- /usr/local/lib/node_modules/cdk-assets/bin/docker-credential-cdk-assets
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/cdk-assets/bin/docker-credential-cdk-assets.js:16:26)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/cdk-assets/bin/docker-credential-cdk-assets.js',
    '/usr/local/lib/node_modules/cdk-assets/bin/docker-credential-cdk-assets'
  ]
}
```

To fix, lets bundle this script as well (in addition to the standard
`cdk-assets` entrypoint).

---
By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache-2.0 license

---------

Signed-off-by: github-actions <github-actions@github.com>
Co-authored-by: github-actions <github-actions@github.com>