docs: add .NET installation prerequisite to CONTRIBUTING.md (#612)
**.NET is required to be installed for initializing or building CDK apps
in C# (and to run associated tests in repo) or else 7 tests fail during
yarn build.**


**Summary of all failing tests (without .NET installed):**

 FAIL  test/cli/cdk-toolkit.test.ts (20.959 s)
  ● migrate › migrate call is idempotent

ToolkitError: Could not add project AutoscalingCSharp.csproj to solution
AutoscalingCSharp.sln. dotnet sln
/var/folders/50/dwz_h2694y1grnyh6y3hxw_r0000gq/T/aws-cdk-testrevTrx/AutoscalingCSharp/src/AutoscalingCSharp.sln
add
/var/folders/50/dwz_h2694y1grnyh6y3hxw_r0000gq/T/aws-cdk-testrevTrx/AutoscalingCSharp/src/AutoscalingCSharp/AutoscalingCSharp.csproj
exited with error code 127

      106 |     } catch (e: any) {
      107 |       if (attempt === MAX_ATTEMPTS) {
> 108 | throw new ToolkitError(`Could not add project ${pname}.${ext} to
solution ${pname}.sln. ${formatErrorMessage(e)}`);
          |               ^
      109 |       }
      110 |
      111 |       // Sleep for a bit then try again

      at dotnetAddProject (lib/commands/init/init-hooks.ts:108:15)
      at InitTemplate.install (lib/commands/init/init.ts:279:5)
      at initializeProject (lib/commands/init/init.ts:515:3)
      at cliInit (lib/commands/init/init.ts:172:5)
      at generateCdkApp (lib/commands/migrate.ts:55:5)
      at CdkToolkit.migrate (lib/cli/cdk-toolkit.ts:1190:7)
      at test/cli/cdk-toolkit.test.ts:1557:5
      at withTempDir (test/cli/cdk-toolkit.test.ts:1906:5)

 FAIL  test/commands/migrate.test.ts (34.105 s)
● Migrate Function Tests › generateCdkApp generates the expected cdk app
when called for csharp

ToolkitError: Could not add project GoodCSharp.csproj to solution
GoodCSharp.sln. dotnet sln
/var/folders/50/dwz_h2694y1grnyh6y3hxw_r0000gq/T/aws-cdk-testH5lbPD/GoodCSharp/src/GoodCSharp.sln
add
/var/folders/50/dwz_h2694y1grnyh6y3hxw_r0000gq/T/aws-cdk-testH5lbPD/GoodCSharp/src/GoodCSharp/GoodCSharp.csproj
exited with error code 127

      106 |     } catch (e: any) {
      107 |       if (attempt === MAX_ATTEMPTS) {
> 108 | throw new ToolkitError(`Could not add project ${pname}.${ext} to
solution ${pname}.sln. ${formatErrorMessage(e)}`);
          |               ^
      109 |       }
      110 |
      111 |       // Sleep for a bit then try again

      at dotnetAddProject (lib/commands/init/init-hooks.ts:108:15)
      at InitTemplate.install (lib/commands/init/init.ts:279:5)
      at initializeProject (lib/commands/init/init.ts:515:3)
      at cliInit (lib/commands/init/init.ts:172:5)
      at generateCdkApp (lib/commands/migrate.ts:55:5)
      at test/commands/migrate.test.ts:308:5
      at withTempDir (test/commands/migrate.test.ts:381:5)

 FAIL  test/commands/init.test.ts (52.199 s)
  ● constructs version › verify "future flags" are added to cdk.json

ToolkitError: Could not add project AwsCdkTestZQm0Yc.csproj to solution
AwsCdkTestZQm0Yc.sln. dotnet sln
/var/folders/50/dwz_h2694y1grnyh6y3hxw_r0000gq/T/aws-cdk-testZQm0yc/src/AwsCdkTestZQm0Yc.sln
add
/var/folders/50/dwz_h2694y1grnyh6y3hxw_r0000gq/T/aws-cdk-testZQm0yc/src/AwsCdkTestZQm0Yc/AwsCdkTestZQm0Yc.csproj
exited with error code 127

      106 |     } catch (e: any) {
      107 |       if (attempt === MAX_ATTEMPTS) {
> 108 | throw new ToolkitError(`Could not add project ${pname}.${ext} to
solution ${pname}.sln. ${formatErrorMessage(e)}`);
          |               ^
      109 |       }
      110 |
      111 |       // Sleep for a bit then try again

      at dotnetAddProject (lib/commands/init/init-hooks.ts:108:15)
      at InitTemplate.install (lib/commands/init/init.ts:279:5)
      at initializeProject (lib/commands/init/init.ts:515:3)
      at cliInit (lib/commands/init/init.ts:172:5)
      at test/commands/init.test.ts:392:11
      at withTempDir (test/commands/init.test.ts:735:5)
      at Object.<anonymous> (test/commands/init.test.ts:391:9)

  ● constructs version › fsharp app with spaces

ToolkitError: Could not add project AwsCdkTestWithSpaceCPiYtx.fsproj to
solution AwsCdkTestWithSpaceCPiYtx.sln. dotnet sln
'/var/folders/50/dwz_h2694y1grnyh6y3hxw_r0000gq/T/aws-cdk-test
with-spaceCPiYtx/src/AwsCdkTestWithSpaceCPiYtx.sln' add
'/var/folders/50/dwz_h2694y1grnyh6y3hxw_r0000gq/T/aws-cdk-test
with-spaceCPiYtx/src/AwsCdkTestWithSpaceCPiYtx/AwsCdkTestWithSpaceCPiYtx.fsproj'
exited with error code 127

      106 |     } catch (e: any) {
      107 |       if (attempt === MAX_ATTEMPTS) {
> 108 | throw new ToolkitError(`Could not add project ${pname}.${ext} to
solution ${pname}.sln. ${formatErrorMessage(e)}`);
          |               ^
      109 |       }
      110 |
      111 |       // Sleep for a bit then try again

      at dotnetAddProject (lib/commands/init/init-hooks.ts:108:15)
      at InitTemplate.install (lib/commands/init/init.ts:279:5)
      at initializeProject (lib/commands/init/init.ts:515:3)
      at cliInit (lib/commands/init/init.ts:172:5)
      at test/commands/init.test.ts:290:5
      at withTempDirWithSpaces (test/commands/init.test.ts:748:5)

  ● constructs version › csharp app with spaces

ToolkitError: Could not add project AwsCdkTestWithSpacezbTern.csproj to
solution AwsCdkTestWithSpacezbTern.sln. dotnet sln
'/var/folders/50/dwz_h2694y1grnyh6y3hxw_r0000gq/T/aws-cdk-test
with-spacezbTERN/src/AwsCdkTestWithSpacezbTern.sln' add
'/var/folders/50/dwz_h2694y1grnyh6y3hxw_r0000gq/T/aws-cdk-test
with-spacezbTERN/src/AwsCdkTestWithSpacezbTern/AwsCdkTestWithSpacezbTern.csproj'
exited with error code 127

      106 |     } catch (e: any) {
      107 |       if (attempt === MAX_ATTEMPTS) {
> 108 | throw new ToolkitError(`Could not add project ${pname}.${ext} to
solution ${pname}.sln. ${formatErrorMessage(e)}`);
          |               ^
      109 |       }
      110 |
      111 |       // Sleep for a bit then try again

      at dotnetAddProject (lib/commands/init/init-hooks.ts:108:15)
      at InitTemplate.install (lib/commands/init/init.ts:279:5)
      at initializeProject (lib/commands/init/init.ts:515:3)
      at cliInit (lib/commands/init/init.ts:172:5)
      at test/commands/init.test.ts:272:5
      at withTempDirWithSpaces (test/commands/init.test.ts:748:5)

  ● constructs version › create a .NET app project in fsharp

ToolkitError: Could not add project AwsCdkTestnKihpy.fsproj to solution
AwsCdkTestnKihpy.sln. dotnet sln
/var/folders/50/dwz_h2694y1grnyh6y3hxw_r0000gq/T/aws-cdk-testnKIHPY/src/AwsCdkTestnKihpy.sln
add
/var/folders/50/dwz_h2694y1grnyh6y3hxw_r0000gq/T/aws-cdk-testnKIHPY/src/AwsCdkTestnKihpy/AwsCdkTestnKihpy.fsproj
exited with error code 127

      106 |     } catch (e: any) {
      107 |       if (attempt === MAX_ATTEMPTS) {
> 108 | throw new ToolkitError(`Could not add project ${pname}.${ext} to
solution ${pname}.sln. ${formatErrorMessage(e)}`);
          |               ^
      109 |       }
      110 |
      111 |       // Sleep for a bit then try again

      at dotnetAddProject (lib/commands/init/init-hooks.ts:108:15)
      at InitTemplate.install (lib/commands/init/init.ts:279:5)
      at initializeProject (lib/commands/init/init.ts:515:3)
      at cliInit (lib/commands/init/init.ts:172:5)
      at test/commands/init.test.ts:250:5
      at withTempDir (test/commands/init.test.ts:735:5)

  ● constructs version › create a .NET app project in csharp

ToolkitError: Could not add project AwsCdkTestNkkhrd.csproj to solution
AwsCdkTestNkkhrd.sln. dotnet sln
/var/folders/50/dwz_h2694y1grnyh6y3hxw_r0000gq/T/aws-cdk-testNkkhrd/src/AwsCdkTestNkkhrd.sln
add
/var/folders/50/dwz_h2694y1grnyh6y3hxw_r0000gq/T/aws-cdk-testNkkhrd/src/AwsCdkTestNkkhrd/AwsCdkTestNkkhrd.csproj
exited with error code 127

      106 |     } catch (e: any) {
      107 |       if (attempt === MAX_ATTEMPTS) {
> 108 | throw new ToolkitError(`Could not add project ${pname}.${ext} to
solution ${pname}.sln. ${formatErrorMessage(e)}`);
          |               ^
      109 |       }
      110 |
      111 |       // Sleep for a bit then try again

      at dotnetAddProject (lib/commands/init/init-hooks.ts:108:15)
      at InitTemplate.install (lib/commands/init/init.ts:279:5)
      at initializeProject (lib/commands/init/init.ts:515:3)
      at cliInit (lib/commands/init/init.ts:172:5)
      at test/commands/init.test.ts:228:5
      at withTempDir (test/commands/init.test.ts:735:5)

Fixes #

---
By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache-2.0 license

Co-authored-by: Momo Kornher <kornherm@amazon.co.uk>