chore: fix logs upload for Node smoke tests (#613)
We used to upload logs with the name of the suite we're running, but now
that we are running the same suite multiple times with different node
versions it's possible to get the following error:

```
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

We need to make the logs entirely unique by including all matrix
parameters.


---
By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache-2.0 license