chore: force minor version bumps for aws-cdk package (#353)
Temporary until we refactor the release process.

Tested locally. When executing `yarn workspaces run bump` on `main`:

```console
👾 Number of commits since aws-cdk@v2.1007.0: 5
✔ bumping version in /Users/epolon/dev/src/github.com/aws/aws-cdk-cli/packages/aws-cdk/package.json from 2.1007.0 to 3.0.0
✔ created /Users/epolon/dev/src/github.com/aws/aws-cdk-cli/packages/aws-cdk/dist/changelog.md
✔ outputting changes to /Users/epolon/dev/src/github.com/aws/aws-cdk-cli/packages/aws-cdk/dist/changelog.md
Error: bump failed: this branch is configured to only publish v2 releases - bump resulted in 3.0.0
    at bump (/Users/epolon/dev/src/github.com/aws/aws-cdk-cli/packages/aws-cdk/node_modules/projen/lib/release/bump-version.js:139:19)
👾 Task "bump" failed when executing ""/opt/homebrew/Cellar/node@20/20.18.0_2/bin/node" "/Users/epolon/dev/src/github.com/aws/aws-cdk-cli/packages/aws-cdk/node_modules/projen/lib/release/bump-version.task.js"" (cwd: /Users/epolon/dev/src/github.com/aws/aws-cdk-cli/packages/aws-cdk)
```

Which fails as expected on the major version protection. When executing
on this branch:

```console
👾 Number of commits since aws-cdk@v2.1007.0: 5
✔ bumping version in /Users/epolon/dev/src/github.com/aws/aws-cdk-cli/packages/aws-cdk/package.json from 2.1007.0 to 2.1008.0
✔ created /Users/epolon/dev/src/github.com/aws/aws-cdk-cli/packages/aws-cdk/dist/changelog.md
✔ outputting changes to /Users/epolon/dev/src/github.com/aws/aws-cdk-cli/packages/aws-cdk/dist/changelog.md
✨  Done in 6.54s.
```

Which correctly bumps from from 2.1007.0 to 2.1008.0.

---
By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache-2.0 license

---------

Signed-off-by: github-actions <github-actions@github.com>
Co-authored-by: github-actions <github-actions@github.com>
Co-authored-by: Rico Hermans <rix0rrr@gmail.com>